# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/docs/sushi/configuration/                    │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: hl7.fhir.us.hsds
canonical: http://hl7.org/fhir/us/hsds

title: "fhir-human-services-directory"
description: "fhir-human-services-directory"
status: draft # draft | active | retired | unknown
name: fhir-human-services-directory
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2022+
releaseLabel: ci-draft
publisher:
  name: HL7 Human and Social Services Work Group
  url: http://www.hl7.org/Special/committees/hsswg/index.cfm
  # email: hsswg@lists.hl7.org

dependencies:
  hl7.fhir.us.core: 3.1.1
  hl7.fhir.us.odh: 1.0.0
  hl7.terminology: 2.1.0
  # hl7.fhir.us.davinci: 1.1.0 
  hl7.fhir.us.davinci-pdex-plan-net: 1.1.0 

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Artifacts: artifacts.html
  Downloads: downloads.html
  Examples: examples.html
  Implementation: implementation.html
