# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/docs/sushi/configuration/                    │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: hl7.fhir.us.hsds
canonical: http://hl7.org/fhir/us/hsds
jurisdiction: urn:iso:std:iso:3166#US
title: "fhir-human-services-directory"
description: "fhir-human-services-directory"
status: active # draft | active | retired | unknown
name: FHIR-Human-Services-Directory
version: 1.0.0
fhirVersion: 4.0.1
license: CC0-1.0
copyrightYear: 2023+
releaseLabel: STU1
publisher:
  name: HL7 Human and Social Services Work Group
  url: http://www.hl7.org/Special/committees/hsswg/index.cfm
  email: hsswg@lists.hl7.org

dependencies:
 hl7.fhir.us.core: 3.1.1
 hl7.fhir.us.davinci-pdex-plan-net: 1.1.0 

parameters:
  show-inherited-invariants: false
#  special-url: [http://hl7.org/fhir/us/hsds/CodeSystem/HumanServiceProgramCS]

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Implementation: 
    Implementation: implementation.html
    Representing and Searching Human Services Directory Data: implementation.html#representing-and-searching-human-services-directory-data
  Artifacts: 
    Profiles: artifacts.html#3
    Extensions: artifacts.html#4
    Terminology: artifacts.html#5
    Search Parameters: artifacts.html#2
    Capability Statement: artifacts.html#1
  Downloads: downloads.html
  Examples: examples.html
  History: http://hl7.org/fhir/us/hsds/history.cfml